"""Tests for NWP ingestion robustness, focusing on duplicate handling and error cases.

This module contains tests that verify the NWP ingestion pipeline handles edge cases
robustly, including:

1. **Temporal deduplication**: When merging multiple forecast steps, duplicate
   timestamps should be handled correctly (last update wins).

2. **Bad Zarr handling**: The pipeline should fail loudly with informative error
   messages when encountering malformed inputs like:
   - Empty Zarr stores
   - Missing critical variables
   - Invalid coordinates

Why we use local Zarr files instead of mocking:
----------------------------------------------
- We test the actual xarray/zarr logic that will be used in production.
- Mocking the API would hide bugs in the temporal merging logic.
- Network dependencies introduce flakiness and slower test execution.
- Static samples enable deterministic, reproducible CI runs.

The test data is generated by `create_production_like_test_zarr.py` which creates:
- A production-like Zarr with spatial coordinates (latitude/longitude)
- Deterministic synthetic data for reproducibility
- Broken Zarr samples for robustness testing

Note on test expectations:
--------------------------
- Tests that require invalid Zarr structures (e.g., missing coordinates) are
  marked with @pytest.mark.xfail because the test Zarr generator intentionally
  avoids creating invalid structure that would break xarray/zarr loading.
- These tests document expected behavior but will fail in xfail mode.
"""

from pathlib import Path


# Use absolute paths - data is created in packages/dynamical_data/example_data
SCRIPT_DIR = Path(__file__).parent.parent
# The script creates data in packages/dynamical_data/src/dynamical_data/example_data/
EXAMPLE_DATA_DIR = SCRIPT_DIR / "packages/dynamical_data/src/dynamical_data/example_data"
TEST_ZARR_PATH = EXAMPLE_DATA_DIR / "ecmwf_production_like.zarr"
BROKEN_ZARR_DIR = EXAMPLE_DATA_DIR / "broken_ecmwf_zarr"
