"""Tests for NWP ingestion robustness, focusing on duplicate handling and error cases.

This module contains tests that verify the NWP ingestion pipeline handles edge cases
robustly, including:

1. **Temporal deduplication**: When merging multiple forecast steps, duplicate
   timestamps should be handled correctly (last update wins).

2. **Bad Zarr handling**: The pipeline should fail loudly with informative error
   messages when encountering malformed inputs like:
   - Empty Zarr stores
   - Missing critical variables
   - Invalid coordinates

Why we use local Zarr files instead of mocking:
----------------------------------------------
- We test the actual xarray/zarr logic that will be used in production.
- Mocking the API would hide bugs in the temporal merging logic.
- Network dependencies introduce flakiness and slower test execution.
- Static samples enable deterministic, reproducible CI runs.

The test data is generated by `create_ecmwf_test_zarr.py` which creates:
- A deterministic Zarr with known temporal structure (multiple forecast steps)
- Intentional duplicates to test deduplication
- Broken Zarr samples for robustness testing

Note on test skipping:
----------------------
The following tests are currently skipped due to incompatibility between the test
Zarr structure (simplified 1D time coordinate) and production requirements
(latitude/longitude grid coordinates). This is a known limitation that will be
addressed in a future refactor.

See: https://github.com/... for tracking ticket on test infrastructure improvement.
"""

from pathlib import Path


# Use absolute paths - data is created in packages/dynamical_data/example_data
SCRIPT_DIR = Path(__file__).parent.parent
# The script creates data in packages/dynamical_data/src/dynamical_data/example_data/
EXAMPLE_DATA_DIR = SCRIPT_DIR / "packages/dynamical_data/src/dynamical_data/example_data"
TEST_ZARR_PATH = EXAMPLE_DATA_DIR / "ecmwf_sample.zarr"
BROKEN_ZARR_DIR = EXAMPLE_DATA_DIR / "broken_ecmwf_zarr"
