power_fcst_model_name: "xgboost"
hyperparameters:
  learning_rate: 0.05
  n_estimators: 500
  max_depth: 6
features:
  nwps:
    - "ecmwf_ens_0_25deg"
  feature_names:
    - "substation_number"
    - "lead_time_hours"
    - "nwp_init_hour"
    - "latest_available_weekly_lag"
    - "temperature_2m"
    - "dew_point_temperature_2m"
    - "wind_speed_10m"
    - "wind_direction_10m"
    - "wind_speed_100m"
    - "wind_direction_100m"
    - "pressure_surface"
    - "pressure_reduced_to_mean_sea_level"
    - "geopotential_height_500hpa"
    - "downward_short_wave_radiation_flux_surface"
    - "categorical_precipitation_type_surface"
    - "windchill"
    - "temperature_2m_lag_7d"
    - "temperature_2m_lag_14d"
    - "temperature_2m_6h_ago"
    - "temp_trend_6h"
    - "downward_short_wave_radiation_flux_surface_lag_7d"
    - "downward_short_wave_radiation_flux_surface_lag_14d"
    - "hour_sin"
    - "hour_cos"
    - "day_of_year_sin"
    - "day_of_year_cos"
    - "day_of_week"
