"""Validate every link to the published docs site resolves to a real page and anchor.

CLAUDE.md requires code and docs outside `docs/` to link to the rendered site
(`https://openclimatefix.github.io/nged-substation-forecast/...`), never a
`github.com/.../blob/main/docs/...` path — but `mkdocs build --strict` validates links *inside*
`docs/` only, so a docstring can point at a page a rename moved, or an anchor a heading rewrite
killed, and nothing notices. This script does.

Two traps a naive implementation hits. First, **never hand-roll a slugify**: Python-Markdown's
`toc` extension preserves underscores (`#step-6-launch-register_experiment_job` is a real anchor
in this repo's own docs), and a guessed `_` → `-` rule reported 15 good links as broken the first
time this was tried. This script instead converts each page with the real `markdown.Markdown()`
converter, using the extensions `mkdocs.yml` configures plus the builtins mkdocs always adds, and
reads the heading ids it actually assigned. Second, `docs/api/*.md` pages hold mkdocstrings
directives (`::: some.module`); their anchors are generated by mkdocstrings at build time, which
this script cannot reproduce, so it checks only that the page exists and reports the anchor check
as skipped.
"""

import difflib
import re
import subprocess
import sys
from collections.abc import Iterator, Sequence
from pathlib import Path
from typing import Any, Final, Literal

import markdown
import yaml

DOCS_SITE_PREFIX: Final[str] = "https://openclimatefix.github.io/nged-substation-forecast/"
"""The canonical spelling of the site root, which CLAUDE.md requires every docs link to use."""

_SITE_ROOT_PATTERN: Final[re.Pattern[str]] = re.compile(
    r"https?://(?:www\.)?" + re.escape(DOCS_SITE_PREFIX.removeprefix("https://"))
)
"""Matches the site root whatever scheme or `www.` prefix it is written with.

A link typo'd as `http://` still points at a page that can be renamed away, so it has to be
checked. Matching only the canonical `https://` spelling would skip it silently — worse than
reporting it, because the summary line would not even count it.
"""

_LINK_PATTERN: Final[re.Pattern[str]] = re.compile(_SITE_ROOT_PATTERN.pattern + r"\S*")

_WRAPPED_ANCHOR_PATTERN: Final[re.Pattern[str]] = re.compile(r"^\s*#(?![#\s])[^\s#]+")
"""Matches a line that opens with an anchor fragment, which means the URL above it wrapped.

A URL reflowed across two lines is broken for the reader as well as for this script: the anchor
is no longer part of the link. Three spellings are deliberately excluded. An ordinary `# comment`
and a `##` markdown heading both put a space or a second `#` after the first one, and the
pattern requires a character after the `#`, which keeps out the bare `#` that separates
paragraphs in a commented file header — `.env.example` has one directly under a docs link.
"""

_TRAILING_SENTENCE_PUNCTUATION: Final[str] = ".,;:!?*_|"
"""Characters that a regex sweep commonly picks up from the prose around a link.

Sentence punctuation, the `*` and `_` of markdown emphasis, and the `|` of a table cell written
without a space. None of these is stripped unconditionally: `_candidate_urls` tries the URL
exactly as written first and only peels when that fails, because a real anchor can end in one of
them. `#credentials-for-our-own-s3-data-data_store_` on the AWS setup page is a live example —
Python-Markdown's slugify drops the `*` from the heading `Credentials ... (DATA_STORE_*)` and
leaves the underscore before it.
"""

_TRAILING_CLOSERS: Final[dict[str, str]] = {")": "(", "]": "[", ">": "<"}
"""Closing bracket -> its opener, used to detect a closer a regex sweep picked up (e.g. the `)`
that closes a markdown `[label](url)`) rather than a closer genuinely part of the URL."""

_TRAILING_SELF_PAIRED: Final[str] = "`'\""
"""Quote/backtick characters: unlike a bracket, these have no distinct opening character to count
a balance against, so instead the whole trailing run of one of them is stripped when the run's
length is odd — see `_strip_trailing_self_paired_run`."""

_BUILTIN_MARKDOWN_EXTENSIONS: Final[tuple[str, ...]] = ("toc", "tables", "fenced_code")
"""Always active in mkdocs regardless of `mkdocs.yml`: `mkdocs.config.defaults.MkDocsConfig`
declares these as `markdown_extensions`' `builtins`. Omitting `fenced_code` in particular would
mis-parse a `#` inside a fenced code block as a heading."""

LinkStatusType = Literal["ok", "skipped_anchor", "bad_page", "bad_anchor", "wrapped"]


def _strip_trailing_self_paired_run(url: str) -> str | None:
    """Strip `url`'s whole trailing run of one `_TRAILING_SELF_PAIRED` character, if odd-length.

    A single trailing quote/backtick (as in a markdown link's own closing punctuation, or a
    quoted URL in prose) is the common case an odd-length run of 1 catches. A Python docstring
    that closes right after a URL puts three trailing double-quote characters after it (the
    closing triple-quote), so stripping one character at a time — re-checking parity after each
    removal — flips odd to even after the first strip and stops with two spurious quotes still
    attached. Counting the run once, up front, and removing it in one step avoids that flip.
    """
    if not url or url[-1] not in _TRAILING_SELF_PAIRED:
        return None
    trimmed = url.rstrip(url[-1])
    return trimmed if (len(url) - len(trimmed)) % 2 == 1 else None


def _peel_one_trailing_character(url: str) -> str | None:
    """Return `url` minus one trailing character a regex sweep may have taken, else `None`."""
    if not url:
        return None
    last = url[-1]
    if last in _TRAILING_SENTENCE_PUNCTUATION:
        return url[:-1]
    opener = _TRAILING_CLOSERS.get(last)
    if opener is not None:
        return url[:-1] if url.count(opener) < url.count(last) else None
    return _strip_trailing_self_paired_run(url)


def _candidate_urls(url: str) -> Iterator[str]:
    """Yield `url` as written, then each shorter form left by peeling trailing punctuation.

    The caller accepts the first candidate that resolves, so peeling only ever runs on a URL that
    already failed. Stripping up front instead damages a real anchor that ends in one of the
    peeled characters — see `_TRAILING_SENTENCE_PUNCTUATION` for the one in these docs today.
    """
    yield url
    candidate = _peel_one_trailing_character(url)
    while candidate is not None:
        yield candidate
        candidate = _peel_one_trailing_character(candidate)


def _iter_links(text: str) -> Iterator[tuple[int, str, bool]]:
    """Yield `(1-indexed line number, url as written, whether the URL wrapped)` for `text`.

    A URL is treated as wrapped when it carries no anchor, ends its own line, and the next line
    holds nothing but an anchor fragment.
    """
    lines = text.splitlines()
    for lineno, line in enumerate(lines, start=1):
        next_line = lines[lineno] if lineno < len(lines) else ""
        for match in _LINK_PATTERN.finditer(line):
            wrapped = (
                match.end() == len(line)
                and "#" not in match.group()
                and _WRAPPED_ANCHOR_PATTERN.match(next_line) is not None
            )
            yield lineno, match.group(), wrapped


def _iter_git_tracked_files() -> Iterator[Path]:
    """Yield every git-tracked file in the repo, relative to the repo root."""
    result = subprocess.run(["git", "ls-files"], capture_output=True, text=True, check=True)
    for line in result.stdout.splitlines():
        yield Path(line)


def _read_text(path: Path) -> str | None:
    """Return `path`'s contents, or `None` if it does not decode as UTF-8 text."""
    try:
        return path.read_text(encoding="utf-8")
    except UnicodeDecodeError, OSError:
        return None


def _resolve_page(docs_dir: Path, url_path: str) -> Path | None:
    """Map a docs-site URL path (e.g. `architecture/performance/`) to its source markdown file.

    Mirrors `use_directory_urls` (mkdocs.yml's default, true): `foo/` may come from either
    `docs/foo.md` or `docs/foo/index.md`, and the empty path is `docs/index.md`.
    """
    stripped = url_path.strip("/")
    if not stripped:
        index = docs_dir / "index.md"
        return index if index.is_file() else None
    for candidate in (docs_dir / f"{stripped}.md", docs_dir / stripped / "index.md"):
        if candidate.is_file():
            return candidate
    return None


def _has_mkdocstrings_directive(path: Path) -> bool:
    """Whether `path` contains a `::: module.path` mkdocstrings directive."""
    text = _read_text(path)
    return text is not None and any(line.strip().startswith(":::") for line in text.splitlines())


def _markdown_extensions_from_mkdocs_yml(
    mkdocs_yml: dict[str, Any],
) -> tuple[list[str], dict[str, dict[str, Any]]]:
    """Return extension names (builtins first) and per-extension config from `mkdocs.yml`.

    `mkdocs.yml`'s `markdown_extensions` list mixes bare names and single-key `{name: config}`
    mappings; malformed or missing entries are treated as "no extensions configured" rather than
    raised, since a config problem here is `mkdocs build`'s job to catch, not this script's.
    """
    names = list(_BUILTIN_MARKDOWN_EXTENSIONS)
    configs: dict[str, dict[str, Any]] = {}
    entries = mkdocs_yml.get("markdown_extensions", [])
    if not isinstance(entries, list):
        return names, configs
    for entry in entries:
        if isinstance(entry, str):
            names.append(entry)
        elif isinstance(entry, dict):
            for name, config in entry.items():
                names.append(name)
                configs[name] = config or {}
    return names, configs


def _walk_toc_ids(tokens: list[dict[str, Any]]) -> Iterator[str]:
    """Yield every heading id in a `markdown.Markdown().toc_tokens` tree, which nests."""
    for token in tokens:
        yield str(token["id"])
        yield from _walk_toc_ids(token.get("children", []))


def _anchors_for_page(
    path: Path,
    extensions: Sequence[str],
    extension_configs: dict[str, dict[str, Any]],
    cache: dict[Path, set[str] | None],
) -> set[str] | None:
    """Return `path`'s heading ids, or `None` if its anchors are mkdocstrings-generated."""
    if path not in cache:
        if _has_mkdocstrings_directive(path):
            cache[path] = None
        else:
            converter = markdown.Markdown(
                extensions=list(extensions), extension_configs=extension_configs
            )
            converter.convert(path.read_text(encoding="utf-8"))
            # `toc_tokens` is added to the instance by the `toc` extension at convert() time, so
            # it isn't part of markdown's own (unstubbed) `Markdown` class.
            cache[path] = set(_walk_toc_ids(converter.toc_tokens))  # ty: ignore[unresolved-attribute]
    return cache[path]


def _check_candidate(
    url: str,
    docs_dir: Path,
    extensions: Sequence[str],
    extension_configs: dict[str, dict[str, Any]],
    anchor_cache: dict[Path, set[str] | None],
) -> tuple[LinkStatusType, str]:
    """Check one exact `url`; return its status and, for a bad anchor, the closest matches."""
    url_path, _, anchor = _SITE_ROOT_PATTERN.sub("", url, count=1).partition("#")
    page = _resolve_page(docs_dir, url_path)
    if page is None:
        return "bad_page", ""
    if not anchor:
        return "ok", ""
    anchors = _anchors_for_page(page, extensions, extension_configs, anchor_cache)
    if anchors is None:
        return "skipped_anchor", ""
    if anchor in anchors:
        return "ok", ""
    close = difflib.get_close_matches(anchor, sorted(anchors), n=5, cutoff=0.3)
    return "bad_anchor", ", ".join(close) if close else "(no close matches on this page)"


def _check_link(
    url: str,
    docs_dir: Path,
    extensions: Sequence[str],
    extension_configs: dict[str, dict[str, Any]],
    anchor_cache: dict[Path, set[str] | None],
) -> tuple[LinkStatusType, str]:
    """Check `url`, accepting the first candidate spelling of it that resolves.

    A candidate that resolves wins outright. When none does, a `bad_anchor` outcome is reported in
    preference to a `bad_page` one, because a resolving page with a wrong anchor tells the author
    more — and comes with the closest real anchors attached.
    """
    worst: tuple[LinkStatusType, str] = ("bad_page", "")
    for candidate in _candidate_urls(url):
        status, detail = _check_candidate(
            candidate, docs_dir, extensions, extension_configs, anchor_cache
        )
        if status in ("ok", "skipped_anchor"):
            return status, detail
        if status == "bad_anchor" and worst[0] == "bad_page":
            worst = (status, detail)
    return worst


def main(argv: list[str]) -> int:
    """Check every docs-site link in `argv`'s files, or the whole repo if `argv` is empty."""
    docs_dir = Path("docs")
    mkdocs_yml = yaml.safe_load(Path("mkdocs.yml").read_text(encoding="utf-8"))
    extensions, extension_configs = _markdown_extensions_from_mkdocs_yml(mkdocs_yml)
    # Construct the converter once, up front, so an extension this script cannot load fails the
    # run here rather than part-way through. Skipping the extension would be worse than crashing:
    # without `pymdownx.superfences` a `#` comment inside an indented fenced code block parses as
    # a heading, so the script would invent anchors the real site does not have and pass links
    # that are broken. Exact parity with the real converter is the whole design.
    try:
        markdown.Markdown(extensions=list(extensions), extension_configs=extension_configs)
    except Exception as exc:
        raise SystemExit(
            f"mkdocs.yml configures a markdown extension this script cannot load: {exc}"
        ) from exc

    paths = [Path(arg) for arg in argv] if argv else list(_iter_git_tracked_files())
    anchor_cache: dict[Path, set[str] | None] = {}
    checked = 0
    bad = 0
    skipped = 0
    for path in paths:
        text = _read_text(path)
        if text is None:
            continue
        for lineno, url, wrapped in _iter_links(text):
            checked += 1
            if wrapped:
                bad += 1
                print(f"{path}:{lineno}: WRAPPED URL {url} (its anchor is on the next line)")
                continue
            status, detail = _check_link(url, docs_dir, extensions, extension_configs, anchor_cache)
            if status == "bad_page":
                bad += 1
                print(f"{path}:{lineno}: BAD PAGE {url}")
            elif status == "bad_anchor":
                bad += 1
                print(f"{path}:{lineno}: BAD ANCHOR {url} (closest: {detail})")
            elif status == "skipped_anchor":
                skipped += 1
                print(f"{path}:{lineno}: SKIPPED anchor check (mkdocstrings page) {url}")

    print(f"checked {checked} links, {bad} bad, {skipped} anchor checks skipped")
    return 1 if bad else 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
