"""Validate every link to the published docs site resolves to a real page and anchor.

CLAUDE.md requires code and docs outside `docs/` to link to the rendered site
(`https://openclimatefix.github.io/nged-substation-forecast/...`), never a
`github.com/.../blob/main/docs/...` path — but `mkdocs build --strict` only validates links
*inside* `docs/`, so a docstring can point at a page a rename moved, or an anchor a heading
rewrite killed, and nothing notices. This script does.

Two traps a naive implementation hits. First, **never hand-roll a slugify**: Python-Markdown's
`toc` extension preserves underscores (`#step-6-launch-register_experiment_job` is a real anchor
in this repo's own docs), and a guessed `_` → `-` rule produced 15 false failures the first time
this was tried. This script instead converts each page with the real `markdown.Markdown()`
converter, using the extensions `mkdocs.yml` configures plus the builtins mkdocs always adds, and
reads the heading ids it actually assigned. Second, `docs/api/*.md` pages hold mkdocstrings
directives (`::: some.module`); their anchors are generated by mkdocstrings at build time, which
this script cannot reproduce, so it checks only that the page exists and reports the anchor check
as skipped.
"""

import difflib
import re
import subprocess
import sys
from collections.abc import Iterator, Sequence
from pathlib import Path
from typing import Any, Final, Literal

import markdown
import yaml

DOCS_SITE_PREFIX: Final[str] = "https://openclimatefix.github.io/nged-substation-forecast/"

_LINK_PATTERN: Final[re.Pattern[str]] = re.compile(re.escape(DOCS_SITE_PREFIX) + r"\S*")

_TRAILING_SENTENCE_PUNCTUATION: Final[str] = ".,;:"
"""Punctuation that ends a sentence and is never part of one of this site's URLs or anchors."""

_TRAILING_CLOSERS: Final[dict[str, str]] = {")": "(", "]": "[", ">": "<"}
"""Closing bracket -> its opener, used to detect a closer a regex sweep picked up (e.g. the `)`
that closes a markdown `[label](url)`) rather than one that is genuinely part of the URL."""

_TRAILING_SELF_PAIRED: Final[str] = "`'\""
"""Quote/backtick characters: unlike a bracket, these have no distinct opening character to count
a balance against, so instead the whole trailing run of one of them is stripped when the run's
length is odd — see `_strip_trailing_self_paired_run`."""

_BUILTIN_MARKDOWN_EXTENSIONS: Final[tuple[str, ...]] = ("toc", "tables", "fenced_code")
"""Always active in mkdocs regardless of `mkdocs.yml`: `mkdocs.config.defaults.MkDocsConfig`
declares these as `markdown_extensions`' `builtins`. Omitting `fenced_code` in particular would
mis-parse a `#` inside a fenced code block as a heading."""

LinkStatusType = Literal["ok", "skipped_anchor", "bad_page", "bad_anchor"]


def _strip_trailing_self_paired_run(url: str) -> str | None:
    """Strip `url`'s whole trailing run of one `_TRAILING_SELF_PAIRED` character, if odd-length.

    A single trailing quote/backtick (as in a markdown link's own closing punctuation, or a
    quoted URL in prose) is the common case an odd-length run of 1 catches. A Python docstring
    that closes right after a URL puts three trailing double-quote characters after it (the
    closing triple-quote), so stripping one character at a time — re-checking parity after each
    removal — flips odd to even after the first strip and stops with two spurious quotes still
    attached. Counting the run once, up front, and removing it in one step avoids that flip.
    """
    if not url or url[-1] not in _TRAILING_SELF_PAIRED:
        return None
    trimmed = url.rstrip(url[-1])
    return trimmed if (len(url) - len(trimmed)) % 2 == 1 else None


def _strip_trailing_punctuation(url: str) -> str:
    """Strip trailing sentence punctuation and unbalanced closers a regex sweep picked up."""
    while url:
        last = url[-1]
        if last in _TRAILING_SENTENCE_PUNCTUATION:
            url = url[:-1]
            continue
        opener = _TRAILING_CLOSERS.get(last)
        if opener is not None:
            if url.count(opener) < url.count(last):
                url = url[:-1]
                continue
            break
        stripped = _strip_trailing_self_paired_run(url)
        if stripped is None:
            break
        url = stripped
    return url


def _iter_links(text: str) -> Iterator[tuple[int, str]]:
    """Yield `(1-indexed line number, cleaned url)` for every docs-site link in `text`."""
    for lineno, line in enumerate(text.splitlines(), start=1):
        for match in _LINK_PATTERN.finditer(line):
            yield lineno, _strip_trailing_punctuation(match.group())


def _iter_git_tracked_files() -> Iterator[Path]:
    """Yield every git-tracked file in the repo, relative to the repo root."""
    result = subprocess.run(["git", "ls-files"], capture_output=True, text=True, check=True)
    for line in result.stdout.splitlines():
        yield Path(line)


def _read_text(path: Path) -> str | None:
    """Return `path`'s contents, or `None` if it does not decode as UTF-8 text."""
    try:
        return path.read_text(encoding="utf-8")
    except UnicodeDecodeError, OSError:
        return None


def _resolve_page(docs_dir: Path, url_path: str) -> Path | None:
    """Map a docs-site URL path (e.g. `architecture/performance/`) to its source markdown file.

    Mirrors `use_directory_urls` (mkdocs.yml's default, true): `foo/` may come from either
    `docs/foo.md` or `docs/foo/index.md`, and the empty path is `docs/index.md`.
    """
    stripped = url_path.strip("/")
    if not stripped:
        index = docs_dir / "index.md"
        return index if index.is_file() else None
    for candidate in (docs_dir / f"{stripped}.md", docs_dir / stripped / "index.md"):
        if candidate.is_file():
            return candidate
    return None


def _has_mkdocstrings_directive(path: Path) -> bool:
    """Whether `path` contains a `::: module.path` mkdocstrings directive."""
    text = _read_text(path)
    return text is not None and any(line.strip().startswith(":::") for line in text.splitlines())


def _markdown_extensions_from_mkdocs_yml(
    mkdocs_yml: dict[str, Any],
) -> tuple[list[str], dict[str, dict[str, Any]]]:
    """Return extension names (builtins first) and per-extension config from `mkdocs.yml`.

    `mkdocs.yml`'s `markdown_extensions` list mixes bare names and single-key `{name: config}`
    mappings; malformed or missing entries are treated as "no extensions configured" rather than
    raised, since a config problem here is `mkdocs build`'s job to catch, not this script's.
    """
    names = list(_BUILTIN_MARKDOWN_EXTENSIONS)
    configs: dict[str, dict[str, Any]] = {}
    entries = mkdocs_yml.get("markdown_extensions", [])
    if not isinstance(entries, list):
        return names, configs
    for entry in entries:
        if isinstance(entry, str):
            names.append(entry)
        elif isinstance(entry, dict):
            for name, config in entry.items():
                names.append(name)
                configs[name] = config or {}
    return names, configs


def _loadable_extensions(names: Sequence[str], configs: dict[str, dict[str, Any]]) -> list[str]:
    """Return the subset of `names` `markdown.Markdown` can actually import.

    `mkdocs.yml` can name an extension only mkdocs or the Material theme understands (a plugin,
    not a Python-Markdown extension); loading it here would raise instead of converting anything,
    so it is dropped, with a warning identifying which one.
    """
    loadable: list[str] = []
    for name in names:
        try:
            markdown.Markdown(extensions=[name], extension_configs={name: configs.get(name, {})})
        except (ImportError, AttributeError, TypeError, KeyError) as exc:
            print(f"warning: cannot load markdown extension {name!r}: {exc}", file=sys.stderr)
            continue
        loadable.append(name)
    return loadable


def _walk_toc_ids(tokens: list[dict[str, Any]]) -> Iterator[str]:
    """Yield every heading id in a `markdown.Markdown().toc_tokens` tree, headings nest."""
    for token in tokens:
        yield str(token["id"])
        yield from _walk_toc_ids(token.get("children", []))


def _anchors_for_page(
    path: Path,
    extensions: Sequence[str],
    extension_configs: dict[str, dict[str, Any]],
    cache: dict[Path, set[str] | None],
) -> set[str] | None:
    """Return `path`'s heading ids, or `None` if its anchors are mkdocstrings-generated."""
    if path not in cache:
        if _has_mkdocstrings_directive(path):
            cache[path] = None
        else:
            converter = markdown.Markdown(
                extensions=list(extensions), extension_configs=extension_configs
            )
            converter.convert(path.read_text(encoding="utf-8"))
            # `toc_tokens` is added to the instance by the `toc` extension at convert() time, so
            # it isn't part of markdown's own (unstubbed) `Markdown` class.
            cache[path] = set(_walk_toc_ids(converter.toc_tokens))  # ty: ignore[unresolved-attribute]
    return cache[path]


def _check_link(
    url: str,
    docs_dir: Path,
    extensions: Sequence[str],
    extension_configs: dict[str, dict[str, Any]],
    anchor_cache: dict[Path, set[str] | None],
) -> tuple[LinkStatusType, str]:
    """Check one docs-site `url`; return its status and, for a bad anchor, the closest matches."""
    rest = url[len(DOCS_SITE_PREFIX) :]
    url_path, _, anchor = rest.partition("#")
    page = _resolve_page(docs_dir, url_path)
    if page is None:
        return "bad_page", ""
    if not anchor:
        return "ok", ""
    anchors = _anchors_for_page(page, extensions, extension_configs, anchor_cache)
    if anchors is None:
        return "skipped_anchor", ""
    if anchor in anchors:
        return "ok", ""
    close = difflib.get_close_matches(anchor, sorted(anchors), n=5, cutoff=0.3)
    return "bad_anchor", ", ".join(close) if close else "(no close matches on this page)"


def main(argv: list[str]) -> int:
    """Check every docs-site link in `argv`'s files, or the whole repo if `argv` is empty."""
    docs_dir = Path("docs")
    mkdocs_yml = yaml.safe_load(Path("mkdocs.yml").read_text(encoding="utf-8"))
    extension_names, extension_configs = _markdown_extensions_from_mkdocs_yml(mkdocs_yml)
    extensions = _loadable_extensions(extension_names, extension_configs)

    paths = [Path(arg) for arg in argv] if argv else list(_iter_git_tracked_files())
    anchor_cache: dict[Path, set[str] | None] = {}
    checked = 0
    bad = 0
    skipped = 0
    for path in paths:
        text = _read_text(path)
        if text is None:
            continue
        for lineno, url in _iter_links(text):
            checked += 1
            status, detail = _check_link(url, docs_dir, extensions, extension_configs, anchor_cache)
            if status == "bad_page":
                bad += 1
                print(f"{path}:{lineno}: BAD PAGE {url}")
            elif status == "bad_anchor":
                bad += 1
                print(f"{path}:{lineno}: BAD ANCHOR {url} (closest: {detail})")
            elif status == "skipped_anchor":
                skipped += 1
                print(f"{path}:{lineno}: SKIPPED anchor check (mkdocstrings page) {url}")

    print(f"checked {checked} links, {bad} bad, {skipped} anchor checks skipped")
    return 1 if bad else 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
