"""Experimental ML model components."""

import logging
from collections.abc import Mapping

import patito as pt
import polars as pl
from contracts.data_schemas import (
    InferenceParams,
    PowerForecast,
    TimeSeriesMetadata,
)
from contracts.hydra_schemas import ModelConfig, NwpModel
from ml_core.model import BaseForecaster

log = logging.getLogger(__name__)


class LocalForecasters(BaseForecaster):
    """Trains and manages a separate BaseForecaster per time series.

    This class implements the BaseForecaster interface by delegating to
    individual forecaster instances for each time series.
    """

    def __init__(self, forecaster_cls: type[BaseForecaster], **forecaster_kwargs):
        """Initialize the local forecasters.

        Args:
            forecaster_cls: The class of the underlying forecaster to use.
            **forecaster_kwargs: Keyword arguments to pass to the forecaster constructor.
        """
        self.forecaster_cls = forecaster_cls
        self.forecaster_kwargs = forecaster_kwargs
        self.models: dict[int | str, BaseForecaster] = {}

    def train(
        self,
        config: ModelConfig,
        flows_30m: pl.LazyFrame,
        time_series_metadata: pt.DataFrame[TimeSeriesMetadata],
        nwps: Mapping[NwpModel, pl.LazyFrame] | None = None,
    ) -> "LocalForecasters":
        """Train a separate model for each time series.

        Args:
            config: Model configuration object.
            flows_30m: Historical power flow data at 30m resolution.
            time_series_metadata: The time series metadata.
            nwps: A dictionary of weather forecast dataframes.

        Returns:
            The trained local forecasters instance.
        """
        time_series_ids = time_series_metadata["time_series_id"].unique().to_list()
        log.info(f"Training local models for {len(time_series_ids)} time series...")

        # TODO: Implement parallelization of this sequential loop
        for ts_id in time_series_ids:
            log.debug(f"Training model for time series {ts_id}")
            ts_meta = time_series_metadata.filter(pl.col("time_series_id") == ts_id)
            ts_flows = flows_30m.filter(pl.col("time_series_id") == ts_id)

            # Instantiate and train
            model = self.forecaster_cls(**self.forecaster_kwargs)
            model.train(
                config=config,
                flows_30m=ts_flows,
                time_series_metadata=ts_meta,
                nwps=nwps,
            )
            self.models[ts_id] = model

        return self

    def predict(
        self,
        time_series_metadata: pt.DataFrame[TimeSeriesMetadata],
        inference_params: InferenceParams,
        flows_30m: pl.LazyFrame,
        nwps: Mapping[NwpModel, pl.LazyFrame] | None = None,
        collapse_lead_times: bool = False,
    ) -> pt.DataFrame[PowerForecast]:
        """Generate power forecasts by routing to local models.

        Args:
            time_series_metadata: The time series metadata.
            inference_params: Parameters for inference.
            flows_30m: Historical power flow data at 30m resolution (for lags).
            nwps: A dictionary of weather forecast dataframes.
            collapse_lead_times: Whether to collapse lead times (used in backtesting).

        Returns:
            A concatenated Patito DataFrame of PowerForecasts.
        """
        all_preds = []
        time_series_ids = time_series_metadata["time_series_id"].unique().to_list()

        for ts_id in time_series_ids:
            if ts_id not in self.models:
                log.warning(f"No model found for time series {ts_id}. Skipping.")
                continue

            ts_meta = time_series_metadata.filter(pl.col("time_series_id") == ts_id)

            # Filter inputs
            ts_flows = flows_30m.filter(pl.col("time_series_id") == ts_id)

            preds = self.models[ts_id].predict(
                time_series_metadata=ts_meta,
                inference_params=inference_params,
                flows_30m=ts_flows,
                nwps=nwps,
                collapse_lead_times=collapse_lead_times,
            )
            all_preds.append(preds)

        if not all_preds:
            raise ValueError("No predictions were generated by any local model.")

        return pt.DataFrame[PowerForecast](pl.concat(all_preds))

    def log_model(self, model_name: str) -> None:
        """Log all local models to MLflow.

        Args:
            model_name: The base name to register the models under.
        """
        raise NotImplementedError("LocalForecasters does not currently support MLflow logging.")
