"""Experimental ML model components."""

import logging
from collections.abc import Mapping

import patito as pt
import polars as pl
from contracts.data_schemas import (
    InferenceParams,
    PowerForecast,
    SubstationMetadata,
)
from contracts.hydra_schemas import ModelConfig, NwpModel
from ml_core.model import BaseForecaster

log = logging.getLogger(__name__)


class LocalForecasters(BaseForecaster):
    """Trains and manages a separate BaseForecaster per substation.

    This class implements the BaseForecaster interface by delegating to
    individual forecaster instances for each substation.
    """

    def __init__(self, forecaster_cls: type[BaseForecaster], **forecaster_kwargs):
        """Initialize the local forecasters.

        Args:
            forecaster_cls: The class of the underlying forecaster to use.
            **forecaster_kwargs: Keyword arguments to pass to the forecaster constructor.
        """
        self.forecaster_cls = forecaster_cls
        self.forecaster_kwargs = forecaster_kwargs
        self.models: dict[int, BaseForecaster] = {}

    def train(
        self,
        config: ModelConfig,
        flows_30m: pl.LazyFrame,
        substation_metadata: pt.DataFrame[SubstationMetadata],
        nwps: Mapping[NwpModel, pl.LazyFrame] | None = None,
    ) -> "LocalForecasters":
        """Train a separate model for each substation.

        Args:
            config: Model configuration object.
            flows_30m: Historical power flow data downsampled to 30m.
            substation_metadata: The substation metadata.
            nwps: A dictionary of weather forecast dataframes.

        Returns:
            The trained local forecasters instance.
        """
        substations = substation_metadata["substation_number"].unique().to_list()
        log.info(f"Training local models for {len(substations)} substations...")

        # TODO: Implement parallelization of this sequential loop
        for sub_num in substations:
            log.debug(f"Training model for substation {sub_num}")
            sub_meta = substation_metadata.filter(pl.col("substation_number") == sub_num)
            sub_flows = flows_30m.filter(pl.col("substation_number") == sub_num)

            # Instantiate and train
            model = self.forecaster_cls(**self.forecaster_kwargs)
            model.train(
                config=config,
                flows_30m=sub_flows,
                substation_metadata=sub_meta,
                nwps=nwps,
            )
            self.models[sub_num] = model

        return self

    def predict(
        self,
        substation_metadata: pt.DataFrame[SubstationMetadata],
        inference_params: InferenceParams,
        flows_30m: pl.LazyFrame,
        nwps: Mapping[NwpModel, pl.LazyFrame] | None = None,
        collapse_lead_times: bool = False,
    ) -> pt.DataFrame[PowerForecast]:
        """Generate power forecasts by routing to local models.

        Args:
            substation_metadata: The substation metadata.
            inference_params: Parameters for inference.
            flows_30m: Historical power flow data downsampled to 30m (for lags).
            nwps: A dictionary of weather forecast dataframes.
            collapse_lead_times: Whether to collapse lead times (used in backtesting).

        Returns:
            A concatenated Patito DataFrame of PowerForecasts.
        """
        all_preds = []
        substations = substation_metadata["substation_number"].unique().to_list()

        for sub_num in substations:
            if sub_num not in self.models:
                log.warning(f"No model found for substation {sub_num}. Skipping.")
                continue

            sub_meta = substation_metadata.filter(pl.col("substation_number") == sub_num)

            # Filter inputs
            sub_flows = flows_30m.filter(pl.col("substation_number") == sub_num)

            preds = self.models[sub_num].predict(
                substation_metadata=sub_meta,
                inference_params=inference_params,
                flows_30m=sub_flows,
                nwps=nwps,
                collapse_lead_times=collapse_lead_times,
            )
            all_preds.append(preds)

        if not all_preds:
            raise ValueError("No predictions were generated by any local model.")

        return pt.DataFrame[PowerForecast](pl.concat(all_preds))

    def log_model(self, model_name: str) -> None:
        """Log all local models to MLflow.

        Args:
            model_name: The base name to register the models under.
        """
        raise NotImplementedError("LocalForecasters does not currently support MLflow logging.")
